[profile.default]
evm_version = 'shanghai'
src = "src"
out = "out"
block_timestamp = 1
verbosity = 3
solc_version = '0.8.20'
optimizer_runs = 0
libs = ["lib", "node_modules"]


[profile.default.rpc_endpoints]
ethereum = "https://eth-mainnet.alchemyapi.io/v2/${ALCHEMY_ETH_MAINNET_KEY}"
goerli = "https://eth-goerli.alchemyapi.io/v2/${ALCHEMY_ETH_GOERLI_KEY}"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_ETH_MAINNET_KEY}"
holesky = "https://ethereum-holesky-rpc.publicnode.com"

polygon = "https://polygon-mainnet.g.alchemy.com/v2/${ALCHEMY_POLYGON_MAINNET_KEY}"
mumbai = "https://polygon-mumbai.g.alchemy.com/v2/${ALCHEMY_POLYGON_MUMBAI_KEY}"

arbitrum = "https://arb-mainnet.g.alchemy.com/v2/${ALCHEMY_ARB_MAINNET_KEY}"

base = "https://base-mainnet.g.alchemy.com/v2/${ALCHEMY_BASE_MAINNET_KEY}"
base-goerli = "https://base-goerli.g.alchemy.com/v2/${ALCHEMY_BASE_TESTNET_KEY}"
basesepolia = "https://base-sepolia.g.alchemy.com/v2/${ALCHEMY_ETH_MAINNET_KEY}"

bsctestnet = "https://bnb-testnet.g.alchemy.com/v2/${ALCHEMY_ETH_MAINNET_KEY}"

blasttestnet = "https://blast-sepolia.g.alchemy.com/v2/${ALCHEMY_ETH_MAINNET_KEY}"
blast = "https://blast-mainnet.g.alchemy.com/v2/${ALCHEMY_ETH_MAINNET_KEY}"

linea = "https://linea-mainnet.g.alchemy.com/v2/${ALCHEMY_ETH_MAINNET_KEY}"

taiko = "https://rpc.mainnet.taiko.xyz"

[etherscan]
ethereum = { key = "${ETHERSCAN_MAINNET_KEY}", chain = 1, url = "https://api.etherscan.io/api?" }
goerli = { key = "${ETHERSCAN_MAINNET_KEY}", chain = 5, url = "https://api-goerli.etherscan.io/api?"}
holesky = {key = "${ETHERSCAN_MAINNET_KEY}", chain = 17000, url = "https://api-holesky.etherscan.io/api?"}
sepolia = { key = "${ETHERSCAN_MAINNET_KEY}", chain = 11155111, url = "https://api-sepolia.etherscan.io/api?"} 

polygon = { key = "${POLYGONSCAN_API_KEY}", chain = 137, url = "https://api.polygonscan.com/api?" }
mumbai = { key = "${POLYGONSCAN_API_KEY}", chain = 80001, url = "https://api-testnet.polygonscan.com/api?" }


base = { key = "${BASESCAN_API_KEY}", chain = 8453 , url = "https://api.basescan.org/api?"}
base-goerli = { key = "${BASESCAN_API_KEY}", chain = 84531, url = "https://api-goerli.basescan.org/api?"}

bsctestnet = { key = "${BSCSCAN_API_KEY}", chain = 97, url = "https://api-testnet.bscscan.com/api?"}

blast = {key = "${BLASTSCAN_API_KEY}", chain = 81457, url = "https://api.blastscan.io/api?"}
blasttestnet = {key = "${BLASTSCAN_API_KEY}", chain = 168587773, url = "https://api-sepolia.blastscan.io/api?"}

basesepolia = {key = "${BASESCAN_API_KEY}", chain = 84532, url="https://api-sepolia.basescan.org/api?"}

linea = {key = "${LINEASCAN_API_KEY}", chain = 59144, url="https://api.lineascan.build/api?"}

taiko = {key = "${TAIKOSCAN_API_KEY}", chain = 167000, url="https://api.taikoscan.io/api?"}

[profile.ci.fuzz]
runs = 10000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
